name: dart_mixpanel
description: Implementation of the mixpanel client library for flutter
homepage: https://foreverday.one
repository: https://github.com/4ed1/dart_mixpanel
issue_tracker: https://github.com/4ed1/dart_mixpanel/issues

version: 0.0.4

dependencies:
    flutter:
        sdk: flutter
    uuid: ">= 2.0.0<= 3.0.4"
    shared_preferences: ">=2.0.4" 
    package_info: ">=0.4.0 <= 2.0.0"
    device_info: ">= 0.4.0 <= 2.0.2"
    http: ">=0.12.0 <= 0.13.3"
    meta: ">=1.1.6 <= 1.7.0" 

environment:
  sdk: ">=2.7.0 <3.0.0"
